### ISSUE TITLE
Tokenizing `grid` property with line names are interpreted incorrectly

### ISSUE THREAD

**Issue by ergunsh** [lezer-parser/css#10]
Hey @marijnh,

It seems like tokenizing this not working correctly:
```css
* {
    grid: [linename1] "a" 100px [linename2];
}
```

The property declaration is resolved to be a `RuleSet` instead of a `Declaration`.

Can you take a look please? :)
