### ISSUE TITLE
Issue with "space" followed by universal selector "*".

### ISSUE THREAD

**Issue by christophsanz** [lezer-parser/css#21]
Any CSS with a space followed by a "*" causes the parser to error right at the space.

Example CSS:

```css
.any-class-or-selector * {
    --variable: blue;
}
```

This is the output of `tree.iterate` logging the `node.name` on enter:

![Image](https://github.com/user-attachments/assets/24105beb-7281-45eb-a832-a1c672ae7d87)

As far as i know this should be valid CSS.

TIA for any Help!
Chris
