### ISSUE TITLE
Scope root and scope limit in @scope not parsed correctly

### ISSUE THREAD

**Issue by SirPepe** [lezer-parser/css#22]
Plain [@scope at-rules](https://developer.mozilla.org/en-US/docs/Web/CSS/@scope) work fine, but  there are parse errors when a scope root and/or scope limit are included.

With only a scope root:

```css
@scope (.parent) {
  .foo {
    color: red;
  }
}
```

Result:

```
StyleSheet(AtRule(AtKeyword,ParenthesizedQuery("(",⚠,KeywordQuery,")"),Block("{",RuleSet(ClassSelector(".",ClassName),Block("{",Declaration(PropertyName,":",ValueName),";","}")),"}")))
```

With scope limit:

```css
@scope (.parent) to (.child) {
  .foo {
    color: red;
  }
}
```

Result:

```
StyleSheet(AtRule(AtKeyword,ParenthesizedQuery("(",⚠,KeywordQuery,")"),⚠),RuleSet(ClassSelector(TagSelector(TagName),⚠("("),".",ClassName),⚠(")"),Block("{",RuleSet(ClassSelector(".",ClassName),Block("{",Declaration(PropertyName,":",ValueName),";","}")),"}")))
```
